#!/usr/bin/env bash
restartupdate () { echo "sleeping for 5 minutes then will try again..."; sleep 300 && aptitude update -y || restartupdate; }
echo "changing password for root..."
passwd root
echo "changing password for kali..."
passwd kali
echo "installing packages"
apt-get install -y aptitude
aptitude update -y || restartupdate
aptitude upgrade -y
aptitude install -y redshift
redshift -O 1337
aptitude install -y fonts-noto-color-emoji
